// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMBnkgZkXBx0n6ET9fa716btbje5um-E',
    appId: '1:291480865463:web:7bbcba0bccba65bc74db32',
    messagingSenderId: '291480865463',
    projectId: 'breakingnews-b4ae9',
    authDomain: 'breakingnews-b4ae9.firebaseapp.com',
    storageBucket: 'breakingnews-b4ae9.appspot.com',
    measurementId: 'G-NNE8PEEHJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmot3E_70WblFQg9WfUtixLIbvulor_Xs',
    appId: '1:291480865463:android:232272193575fd8b74db32',
    messagingSenderId: '291480865463',
    projectId: 'breakingnews-b4ae9',
    storageBucket: 'breakingnews-b4ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcct1Tk_P9khwepiI3-iifv0sV7ZdD7MQ',
    appId: '1:291480865463:ios:d4a2f795f3e33e4274db32',
    messagingSenderId: '291480865463',
    projectId: 'breakingnews-b4ae9',
    storageBucket: 'breakingnews-b4ae9.appspot.com',
    iosBundleId: 'com.example.newsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcct1Tk_P9khwepiI3-iifv0sV7ZdD7MQ',
    appId: '1:291480865463:ios:d4a2f795f3e33e4274db32',
    messagingSenderId: '291480865463',
    projectId: 'breakingnews-b4ae9',
    storageBucket: 'breakingnews-b4ae9.appspot.com',
    iosBundleId: 'com.example.newsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMBnkgZkXBx0n6ET9fa716btbje5um-E',
    appId: '1:291480865463:web:353d4ace1ae4afc574db32',
    messagingSenderId: '291480865463',
    projectId: 'breakingnews-b4ae9',
    authDomain: 'breakingnews-b4ae9.firebaseapp.com',
    storageBucket: 'breakingnews-b4ae9.appspot.com',
    measurementId: 'G-XC4M4303KQ',
  );
}
